=== metadatacenter/cedar-artifact-server/cedar-template-server-application/src/test/resources/templates/empty-template.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "@id": "https://repo.metadatacenter.orgx/templates/8d8eeeae-ca63-42e6-8090-0dfd1203f8c8",
    "@type": "https://schema.metadatacenter.org/core/Template",
    "@context": {
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "pav": "http://purl.org/pav/",
        "oslc": "http://open-services.net/ns/core#",
        "schema": "http://schema.org/",
        "pav:createdOn": {
            "@type": "xsd:dateTime"
        },
        "pav:createdBy": {
            "@type": "@id"
        },
        "pav:lastUpdatedOn": {
            "@type": "xsd:dateTime"
        },
        "oslc:modifiedBy": {
            "@type": "@id"
        }
    },
    "type": "object",
    "title": "Empty template template schema template schema",
    "description": "Empty template template schema template schema autogenerated by the CEDAR Template Editor 1.0.3",
    "_ui": {
        "title": "Empty template template schema",
        "description": "Empty template template schema autogenerated by the CEDAR Template Editor",
        "pages": [],
        "order": []
    },
    "properties": {
        "@context": {
            "type": "object",
            "properties": {
                "xsd": {
                    "type": "string",
                    "format": "uri",
                    "enum": [
                        "http://www.w3.org/2001/XMLSchema#"
                    ]
                },
                "pav": {
                    "type": "string",
                    "format": "uri",
                    "enum": [
                        "http://purl.org/pav/"
                    ]
                },
                "schema": {
                    "type": "string",
                    "format": "uri",
                    "enum": [
                        "http://schema.org/"
                    ]
                },
                "oslc": {
                    "type": "string",
                    "format": "uri",
                    "enum": [
                        "http://open-services.net/ns/core#"
                    ]
                },
                "schema:isBasedOn": {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "enum": [
                                "@id"
                            ]
                        }
                    }
                },
                "schema:name": {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "enum": [
                                "xsd:string"
                            ]
                        }
                    }
                },
                "schema:description": {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "enum": [
                                "xsd:string"
                            ]
                        }
                    }
                },
                "pav:createdOn": {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "enum": [
                                "xsd:dateTime"
                            ]
                        }
                    }
                },
                "pav:createdBy": {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "enum": [
                                "@id"
                            ]
                        }
                    }
                },
                "pav:lastUpdatedOn": {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "enum": [
                                "xsd:dateTime"
                            ]
                        }
                    }
                },
                "oslc:modifiedBy": {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "type": "string",
                            "enum": [
                                "@id"
                            ]
                        }
                    }
                }
            },
            "patternProperties": {
                "^(?!pav)(?!schema)(?!oslc)[a-zA-Z][a-zA-Z0-9]*$": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "xsd",
                "pav",
                "schema",
                "oslc",
                "schema:isBasedOn",
                "schema:name",
                "schema:description",
                "pav:createdOn",
                "pav:createdBy",
                "pav:lastUpdatedOn",
                "oslc:modifiedBy"
            ],
            "additionalProperties": false
        },
        "@id": {
            "type": [
                "string",
                "null"
            ],
            "format": "uri"
        },
        "@type": {
            "oneOf": [
                {
                    "type": "string",
                    "format": "uri"
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string",
                        "format": "uri"
                    },
                    "uniqueItems": true
                }
            ]
        },
        "schema:isBasedOn": {
            "type": "string",
            "format": "uri"
        },
        "schema:name": {
            "type": "string",
            "minLength": 1
        },
        "schema:description": {
            "type": "string"
        },
        "pav:createdOn": {
            "type": [
                "string",
                "null"
            ],
            "format": "date-time"
        },
        "pav:createdBy": {
            "type": [
                "string",
                "null"
            ],
            "format": "uri"
        },
        "pav:lastUpdatedOn": {
            "type": [
                "string",
                "null"
            ],
            "format": "date-time"
        },
        "oslc:modifiedBy": {
            "type": [
                "string",
                "null"
            ],
            "format": "uri"
        }
    },
    "required": [
        "@id",
        "schema:isBasedOn",
        "schema:name",
        "schema:description",
        "pav:createdOn",
        "pav:createdBy",
        "pav:lastUpdatedOn",
        "oslc:modifiedBy"
    ],
    "pav:createdOn": null,
    "pav:createdBy": null,
    "pav:lastUpdatedOn": null,
    "oslc:modifiedBy": null,
    "additionalProperties": false
}

=== metadatacenter/cedar-artifact-server/cedar-template-server-application/src/test/resources/crud/SampleTemplateInstance.json
{
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "pav": "http://purl.org/pav/",
    "schema": "http://schema.org/",
    "oslc": "http://open-services.net/ns/core#",
    "schema:isBasedOn": {
      "@type": "@id"
    },
    "schema:name": {
      "@type": "xsd:string"
    },
    "schema:description": {
      "@type": "xsd:string"
    },
    "pav:createdOn": {
      "@type": "xsd:dateTime"
    },
    "pav:createdBy": {
      "@type": "@id"
    },
    "pav:lastUpdatedOn": {
      "@type": "xsd:dateTime"
    },
    "oslc:modifiedBy": {
      "@type": "@id"
    }
  },
  "schema:isBasedOn": "https://repo.metadatacenter.orgx/templates/8558e0c5-c123-431f-beda-9ed5e75f0d2c",
  "schema:name": "Untitled metadata",
  "schema:description": "Description",
  "pav:createdOn": "2017-04-07T12:10:37-0700",
  "pav:createdBy": "https://metadatacenter.org/users/8d787b98-33dd-4aff-a88c-440caf452c61",
  "pav:lastUpdatedOn": "2017-04-07T12:10:37-0700",
  "oslc:modifiedBy": "https://metadatacenter.org/users/8d787b98-33dd-4aff-a88c-440caf452c61",
  "@id": "https://repo.metadatacenter.orgx/template-instances/697bf2ba-bde1-46ec-97a3-9f4c3eb5af01"
}
